### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by mongrelion** [mongrelion/ansible-role-docker#13]
Our current test suite has several issues:

1. It's not automated. If we are to make sure that a developer's change hasn't broken anything, someone has to pull their changes, run the test suite locally and make sure that everything is working accordingly, which bring us to the second point

2. There are no tests whatsoever. The only thing that we are doing is applying the `ansible-role-docker` role with Ansible to the VMs that we create and assume that if no task failed during the run of the playbook, then everything is "fine". We should have a proper test suite that automates all of this, and that has a decent criteria to ensure that the role has been applied successfully and that the installed software (Docker) is behaving as expected (config files in place with proper config params, daemon running & logging, etc.)

Possible options for aiding to this issue are:
* http://serverspec.org/
* https://www.inspec.io/
* https://testinfra.readthedocs.io/en/latest/

If someone has the knowledge or time to dive into testing these tools out (or if they have a better suggestion in mind) and write down below a list of pros/cons for each, that would be great. Otherwise I'll find the time later in August to try them all out with very simple use cases and pick the one that I like the most :P

**Comment by brucellino** [comment]
hi @mongrelion how is work going on this issue ? I would like to lend a hand.

**Comment by mongrelion** [comment]
Hello, @brucellino 

Thanks for your interest. Please take a look at PR #30 
@paulfantom is already on it and for sure could use a helping hand.
