### ISSUE TITLE
Role blocks when docker is already installed

### ISSUE THREAD

**Issue by mhutter** [mongrelion/ansible-role-docker#16]
Recent versions of the docker setup script by Rancher has a 20sec `sleep` implemented when docker is already installed. This causes this role to block 20sec on each run once docker is set up.

Possible solution: Only run the "Execute docker setup script" step when no `/usr/bin/docker` is present.

This would also alleviate the issue that when the installed version is more recent than the default in this playbook, the playbook won't crash anymore (it currently does that because the script tries to downgrade docker which fails)

**Comment by mongrelion** [comment]
@marcusianlevine you did the whole Rancher installation script integration. What do you think?

**Comment by marcusianlevine** [comment]
Agree with @mhutter that this behavior is not ideal and to maintain idempotency we should be checking if Docker is installed before trying to run the setup script.

I think the fix in PR #17 makes sense, but two edge cases come to mind:
1. If there is already a statically linked version of the Docker client binary for whatever reason on the host being configured, the Docker daemon will not be installed. Maybe we could check for both `/usr/bin/docker` and something that will only be present if the daemon is installed like `/var/lib/docker`
2. Deliberately re-running the role to upgrade an existing Docker installation. I understand downgrading is currently broken, but upgrading _should_ work.

As long as there is an override flag to force the setup script to run even if a `/usr/bin/docker` binary is present we should make this the default behavior.

**Comment by mhutter** [comment]
Good points from @marcusianlevine.

1. This could be mitigated by checking for `dockerd` instead. Do you think this would take care of this edge case?
2. I could add a parameter like `upgrade_docker` which would force the script to be updated and run - as far as I observed this would not work at the moment either, because the script is only downloaded once.

**Comment by marcusianlevine** [comment]
@mhutter 

1. Yes, that addresses the case I was concerned about here.
2. This sounds like a good solution to me. I'm not sure what you mean when you say the "script is only downloaded once." If one intends to install a different version of Docker with this role, an override for the `docker_version` parameter and the script checksum would be provided, in which case the [`get_url` module would detect that the destination checksum does not match the specified checksum and re-download the file](http://docs.ansible.com/ansible/latest/get_url_module.html). 

I think once these changes are reflected in PR #17 we can merge in

**Comment by mhutter** [comment]
I updated #17 to address the issues.
