### ISSUE TITLE
md5sum of docker setup script changed.

### ISSUE THREAD

**Issue by sardoodledom** [mongrelion/ansible-role-docker#19]
I get this error when running the playbooks. Just wanted to give a heads up.
"The checksum for /tmp/docker-setup.sh did not match 659c2c28875469d68b14a71e44cb281f; it was 6be324016277879d49bd0e7f9f91e546."
Confirmed on my host with curl:
curl https://releases.rancher.com/install-docker/17.06.sh -o /tmp/17.06.sh && md5sum /tmp/17.06.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15228  100 15228    0     0  33058      0 --:--:-- --:--:-- --:--:-- 33032
6be324016277879d49bd0e7f9f91e546  /tmp/17.06.sh

**Comment by marcusianlevine** [comment]
Closing this since merged in #18
