### ISSUE TITLE
`docker daemon` is not supported on Linux. Please run `dockerd` directly

### ISSUE THREAD

**Issue by jensbaitingerbosch** [mongrelion/ansible-role-docker#22]
docker daemon command is deprecated and comes only when the docker client is built with a special flag (see [here](https://github.com/docker/for-linux/issues/11)) 

Occured with the default setting (17.06) as well as the current 17.09.

Suggestions: as the error message suggests the service file should use the `dockerd` command instead of `docker daemon`.

**Comment by marcusianlevine** [comment]
@jensbaitingerbosch this should be a quick one-line fix in [templates/docker.j2.service](https://github.com/mongrelion/ansible-role-docker/blob/master/templates/docker.j2.service) if you'd like to contribute a PR for this!

**Comment by yanky83** [comment]
Hey, 
I ran into the same issue. May I ask, what is the purpose of overwriting the service script in the first place?

**Comment by mongrelion** [comment]
Fixed in PR #29
