### ISSUE TITLE
Support for proxy in docker daemon is missing

### ISSUE THREAD

**Issue by ageekymonk** [mongrelion/ansible-role-docker#25]
Hi, 

   If proxy needs to be configured for docker daemon, it is not supported in the daemon.json file. It has to be in the /etc/systemd/system/docker.service.d/http-proxy.conf. 
  
FYI https://docs.docker.com/engine/admin/systemd/#httphttps-proxy
Thanks

**Comment by mongrelion** [comment]
@ageekymonk do you think that you can submit a PR for this?

**Comment by ageekymonk** [comment]
sure. Is it okay if i add *docker_http_proxy* , *docker_https_proxy*, and *docker_no_proxy* as variable name to be passed in ?

**Comment by mongrelion** [comment]
Sounds good to me!
