### ISSUE TITLE
Can we start Tagging releases please

### ISSUE THREAD

**Issue by llbbl** [mongrelion/ansible-role-docker#27]
I am actually using versioning and finding it helpful. 

http://docs.ansible.com/ansible/latest/galaxy.html#version

It doesn't have to be SemVer, but a tag every now and then when you think of it.  Someone with commit access to this repo has to do it. Tags can't be added via Pull Requests. :(

**Comment by mongrelion** [comment]
I like the idea of tagging the repo, specially semver.
Right now there is no roadmap so it's hard to point to a specific version so I'm going to start with `0.1.0` and take it from there.
I'm not in my computer atm, though, so this will have to wait until tomorrow.

Thanks for this, @llbbl !

**Comment by mongrelion** [comment]
Done
