### ISSUE TITLE
Unify variable naming

### ISSUE THREAD

**Issue by paulfantom** [mongrelion/ansible-role-docker#32]
From my experience it is generally easier to read playbook vars or group vars when roles use some prefix in their variable naming convention. This way it is very easy to identify which variable overwrites which role defaults.

I propose to change all variables located in defaults/main.yml to be prefixed with "docker_" and provide a task file which would map old variables to new ones by using `set_fact` module. This way role could be backwards compatible and provide this namespace functionality.

**Comment by mongrelion** [comment]
I like this idea very much. Let's also plan how we're going to deprecate the old variables at some point. I'm ok with backwards compatibility but we should not let legacy get on the way of progress.
We already started using semver. I would prefer to just update the README giving users the instructions on how to use the role with the old version that won't break it for them.
