### ISSUE TITLE
docker-compose ?

### ISSUE THREAD

**Issue by paulfantom** [mongrelion/ansible-role-docker#39]
Currently role can install `docker-py` which is outdated (current name is just `docker`) and not really usable anywhere outside some application. Maybe we should dump installing `docker-py` and just install `docker-compose` since it also includes correct docker python library and can be used for some other things.

@mongrelion what do you think about it?

**Comment by rdemachkovych** [comment]
Installing docker-compose is a good idea as it often used with Docker

**Comment by mongrelion** [comment]
I agree. I don't even remember anymore why this was included in the role.
Also, indeed, `docker-compose` is quite commonly shipped with `docker` itself.
