### ISSUE TITLE
Ubuntu Bionic support

### ISSUE THREAD

**Issue by dixhuit** [mongrelion/ansible-role-docker#52]
Just tried your role with Ubuntu Bionic and it fails (fair enough, your meta only states that you support Ubuntu Xenial).

That said, I reckon you only need add some logic for adding the `edge` option to the apt repo and it would work. Docker docs state that 18.04 is supported but via "Docker CE 18.05 Edge and higher only".

https://docs.docker.com/install/linux/docker-ce/ubuntu/#os-requirements

To test I knocked up a role that used the following and it installed fine:

```
apt_repository:
  repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable edge"
```
Would you consider a PR?

**Comment by SISheogorath** [comment]
I don't think that it's a good idea to switch to edge here.

Also this month the new stable comes out which supports bionic so I think it's easier to wait a few more days. But maybe in general an option for "edge vs stable" would be an idea :)

**Comment by dixhuit** [comment]
> you only need add some logic for adding the edge option

I only ever meant to suggest adding a general option, never to "switch".

I wasn't aware that the new stable was due to come out so soon though so thanks for that info, I'll aim to switch to your role when that lands. Do you have a link that can help me track when the new stable version is released?

**Comment by paulfantom** [comment]
@danbohea docker releases stable versions every quarter starting from version 17.03 (17 - year, 03 - month).

Info from https://docs.docker.com/install/, section "Time-based release schedule"

**Comment by dixhuit** [comment]
Many thanks.

**Comment by mongrelion** [comment]
Continuing this discussion, though.
Is it a good idea to support edge releases on the major distros? Debian test, Ubuntu edge, CentOS whateveritscalled?

**Comment by paulfantom** [comment]
Docker releases security fixes when needed and we get stable versions every 3 months, so I am not very eager to include 'edge' version. However if we want it, this shouldn't be very hard to implement.

**Comment by mongrelion** [comment]
I share your view, @paulfantom 
If users want this feature implemented, we're happy to look into it.
@danbohea for you'll just have to be a little patient :)

Closing this for now until more people want this feature.
